version: '3.7'
services: 
  flask-app:
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
  mysql:    
    build: ./db
    environment: 
      MYSQL_DATABASE: ${flask-db}
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
    ports:
    - target: 3306
      published: 3306       
      protocol: tcp 
